insert into user values ('denis','denis_login','ltybc@gmail.com', 'password')
-- insert into user values ('vovan','vovan_login','vovan@gmail.com', 'password')
-- insert into user values ('admin','admin_login','admin@gmail.com', 'password')
-- insert into user values ('rootu','rootu_login','rootu@gmail.com', 'password')
-- insert into user values ('peppe','peppe_login','peppe@gmail.com', 'password')